### ISSUE TITLE
the plugin is not working 

### ISSUE THREAD

**Issue by khaled-elbehery** [Joel2B/video-player-wordpress-plugin#1]
the plugin is not working please fix it .
thank you so much

in wp-admin/admin.php?page=cvp-dashboard 
Error getting changelog

in wp-admin/admin.php?page=logs-page 

[{"date":"2022-02-27 13:32:19","type":"error","file_uri":"../wp-content/plugins/video-player-wordpress-plugin-main/public/classes/class-encryption.php","file_line":0,"code":0,"message":"unsuccessful decryption <code>0</code>\n","product":"Video Player Wordpress Plugin Main","class":"label-danger"}]

**Comment by Joel2B** [comment]
i just did a clean install and it's working perfectly
with php 7.4 and wordpress 5.9.1

seems that the iframe link is not being generated properly, could you send the link
that is generated in the iframe?

**Comment by khaled-elbehery** [comment]
thank you so much for your response i really appreciate it .

Let me explain exactly what happened
When I installed the plugin it worked perfectly.
And it transformer the iframe to the video player inside the posts, and the videos worked without any error.
But after several hours, I found that all the videos are not working, and the phrase (the video is not available) appears instead.
Related videos appear on the video player.
And the situation remained like this for many hours, then by itself the videos worked again inside the video player without a problem for several hours.
And so it goes again and again.
The plugin works for several hours and stops for several hours.
In any case, the plugin converts scr inside an iframe to .

https://site.com/?cvp_data=$_$_oP_X4Jz7zXwA(Qd5paTJ)dSX

In the event that the plugin works, the source is inside this link
it contains .

<video id="video-player" poster="https://img-hw.xvideos-cdn.com/videos/thumbs169lll/1a/28/5e/1a285e5c6db86bb14174a70deafd2143/1a285e5c6db86bb14174a70deafd2143.15.jpg"><source src="https://cdn77-vid.xvideos-cdn.com/rTU-uKC-bdriwb9tEc3TPw==,1646218665/videos/hls/1a/28/5e/1a285e5c6db86bb14174a70deafd2143/hls.m3u8" type="application/x-mpegURL" title="all"></source></video><div id="related-videos" class="related"><h1 class="title">Related videos</h1>

In this case, it appears 
in wp-admin/admin.php?page=cvp-dashboard
Added: Initial release
.
And it works perfectly .

But when the plugin stops, the source contains only Related videos.
In this case, it appears 
in wp-admin/admin.php?page=cvp-dashboard
Error getting changelog


At the moment I am writing this reply
The plugin is working fine.
I hope I explained the problem well .

**Comment by Joel2B** [comment]
i just checked everything and looks like everything is fine.

the only thing i can see is that the plugin is in the video-player-wordpress-plugin-main folder, 
which should be "custom-video-player",
because the API (for updates) only detects the "custom-video-player" folder, 
if is another may not work.

try renaming the folder to "custom-video-player" and let me know if still crashes

**Comment by khaled-elbehery** [comment]
yes i renaming the folder to "custom-video-player"
but unfortunately still crashes .
its crashes right now .

wp-admin/admin.php?page=cvp-dashboard
Error getting changelog


`[{"date":"2022-03-01 22:35:30","type":"error","file_uri":"../wp-content/plugins/custom-video-player/custom-video-player.php","file_line":0,"code":0,"message":"Connection to API (changelog) failed\n","product":"Custom Video Player","class":"label-danger"},{"date":"2022-03-02 12:08:21","type":"error","file_uri":"../wp-content/plugins/custom-video-player/custom-video-player.php","file_line":0,"code":0,"message":"Connection to API (changelog) failed\n","product":"Custom Video Player","class":"label-danger"},{"date":"2022-03-02 12:09:12","type":"error","file_uri":"../wp-content/plugins/custom-video-player/custom-video-player.php","file_line":0,"code":0,"message":"Connection to API (changelog) failed\n","product":"Custom Video Player","class":"label-danger"},{"date":"2022-03-02 20:05:45","type":"error","file_uri":"../wp-content/plugins/custom-video-player/public/classes/class-encryption.php","file_line":0,"code":0,"message":"unsuccessful decryption <code>0</code>\n","product":"Custom Video Player","class":"label-danger"},{"date":"2022-03-02 23:03:56","type":"error","file_uri":"../wp-content/plugins/custom-video-player/public/classes/class-encryption.php","file_line":0,"code":0,"message":"unsuccessful decryption <code>0</code>\n","product":"Custom Video Player","class":"label-danger"},{"date":"2022-03-03 01:48:06","type":"error","file_uri":"../wp-content/plugins/custom-video-player/public/classes/class-encryption.php","file_line":0,"code":0,"message":"unsuccessful decryption <code>0</code>\n","product":"Custom Video Player","class":"label-danger"},{"date":"2022-03-03 01:50:12","type":"error","file_uri":"../wp-content/plugins/custom-video-player/custom-video-player.php","file_line":0,"code":0,"message":"Connection to API (changelog) failed\n","product":"Custom Video Player","class":"label-danger"},{"date":"2022-03-03 01:51:19","type":"error","file_uri":"../wp-content/plugins/custom-video-player/public/classes/class-encryption.php","file_line":0,"code":0,"message":"unsuccessful decryption <code>0</code>\n","product":"Custom Video Player","class":"label-danger"},{"date":"2022-03-03 01:52:12","type":"error","file_uri":"../wp-content/plugins/custom-video-player/custom-video-player.php","file_line":0,"code":0,"message":"Connection to API (changelog) failed\n","product":"Custom Video Player","class":"label-danger"},{"date":"2022-03-03 01:52:15","type":"error","file_uri":"../wp-content/plugins/custom-video-player/custom-video-player.php","file_line":0,"code":0,"message":"Connection to API (changelog) failed\n","product":"Custom Video Player","class":"label-danger"}]`

**Comment by Joel2B** [comment]
try doing a `curl -i` to 

https://appsdev.cyou/products/CVP/changelog
https://appsdev.cyou/products/CVP/details
https://appsdev.cyou/xv-ph-rt/api/?site_id=pornhub&video_id=ph6116a13a48187

should return the content,
if not, maybe there is some blocking by the origin server / cloudflare

if you can try from another server

and if still doesn't work, you can use the "WPS Player" plugin in
https://appsdev.cyou/wp-script-api/

which does the same as this one, but without using an API and is maintained by others

meanwhile i do more tests

**Comment by khaled-elbehery** [comment]
sometimes return the content, 
but most of the time Redirecting to 404 page


the Source before  Redirecting to 404 page 

`<html>
<body>


<html>
--
  | <head>
  | <meta charset="utf-8">
  | <meta name="robots" content="noindex, nofollow">
  | <title>One moment, please...</title>
  | <style>
  | body {
  | background: #F6F7F8;
  | color: #303131;
  | font-family: sans-serif;
  | margin-top: 45vh;
  | text-align: center;
  | }
  | </style>
  | </head>
  | <body>
  | <h1>Please wait while your request is being verified...</h1>
  | <form id="wsidchk-form" style="display:none;" action="/z0f76a1d14fd21a8fb5fd0d03e0fdc3d3cedae52f" method="get">
  | <input type="hidden" id="wsidchk" name="wsidchk" />
  | </form>
  | <script>
  | (function(){
  | var west=+((+!+[]+!![]+!![]+!![]+!![]+!![]+!![])+(+![]+[])+(+!+[]+!![]+!![]+!![]+!![]+!![]+!![])+(+![]+[])+(+!+[]+!![]+!![]+!![]+!![]+!![]+!![])+(+!+[]+!![]+!![]+!![]+!![]+!![]+[])+(+!+[]+!![])),
  | east=+((+!+[])+(+!+[]+!![]+!![]+!![]+[])+(+!+[]+!![]+!![])+(+![]+[])+(+!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(+!+[]+[])+(+!+[])+(+!+[]+!![]+!![]+!![]+!![]+[])),
  | x=function(){try{return !!window.addEventListener;}catch(e){return !!0;} },
  | y=function(y,z){x() ? document.addEventListener("DOMContentLoaded",y,z) : document.attachEvent("onreadystatechange",y);};
  | y(function(){
  | document.getElementById('wsidchk').value = west + east;
  | document.getElementById('wsidchk-form').submit();
  | }, false);
  | })();
  | </script>
  | </body>
  | </html>


</body>
</html>`

**Comment by Joel2B** [comment]
i did a quick research and looks like a cloudflare verification

https://community.cloudflare.com/t/how-to-submit-our-crawler-as-cloudflare-verified-bot/354976

i have applied some firewall rules for those routes, 
but i don't know if works, tell me if there were any changes

**Comment by khaled-elbehery** [comment]
Well the plugin is working fine now.
I hope for continued support and development for this plugin .
Thank you so much .

**Comment by Joel2B** [comment]
perfect!

feel free to suggest any functionality and report any bugs
